//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK.GeometryLib.AreaMapFramework.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TK.GeometryLib.AreaMapFramework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;AreaMap xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Name&gt;Library&lt;/Name&gt;
        ///  &lt;ImagePath /&gt;
        ///  &lt;Areas&gt;
        ///    &lt;Area&gt;
        ///      &lt;Name&gt;L_Arm&lt;/Name&gt;
        ///      &lt;MetaData /&gt;
        ///      &lt;Description /&gt;
        ///      &lt;IsActive&gt;true&lt;/IsActive&gt;
        ///      &lt;IsVisible&gt;true&lt;/IsVisible&gt;
        ///      &lt;Type&gt;Polygon&lt;/Type&gt;
        ///      &lt;Shape xsi:type=&quot;Polygon2&quot;&gt;
        ///        &lt;Center&gt;
        ///          &lt;X&gt;358&lt;/X&gt;
        ///          &lt;Y&gt;222&lt;/Y&gt;
        ///        &lt;/Center&gt;
        ///        &lt;Points&gt;        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap no_image {
            get {
                object obj = ResourceManager.GetObject("no_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à # Copyright (c) 2012-2013 Guillaume Barlier
        ///# This file is a data file for the anim_picker tool.
        ///# The &quot;anim_picker&quot; tool is covered by the LGPLv3 or later,
        ///# read COPYING and COPYING.LESSER for details.
        ///# The tool can be downloaded from: http://guillaume.barlier.com/code
        ///
        ///#This is a version that was initially exported from Toonkit tool &quot;SynopTiK&quot; (http://toonkit-studio.com)
        ///#It does not extend neither cancel initial LGPLv3 and anim_picker Guillaume Barlier&apos;s ownership
        ///
        ///&lt;data_start/&gt;
        ///{&apos;tabs&apos;: [{&apos;d [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string skeleton {
            get {
                return ResourceManager.GetString("skeleton", resourceCulture);
            }
        }
    }
}
